In [1]:
#import library yang di butuhkan
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import LinearSVC

In [2]:
#create classfier
lr = LogisticRegression(solver='lbfgs')
svc = LinearSVC(C = 1.0)
rfc = RandomForestClassifier(n_estimators = 100)


In [3]:
#mengimport dataset train
df = pd.read_csv('Train1.csv',sep = ';')
df.head(5)

NISN  Nama   Umur   Kelas  Rerata UN  Rata­rata Nilai Sekolah      Hasil
0  27786  Akbar     17  IPA 1         87                       83      Lolos
1  38539  Opang     17  IPA 2         83                       91      Lolos
2  47031  Erwan     18  IPA 2         91                       84      Lolos
3  58624   Kaka     17  IPS 3         90                      100      Lolos
4  68091   Cimo     17  IPS 4         82                       75  Coba lagi

In [4]:
# menghapus kolom yang tidak dibutuhkan
df = df.drop(["NISN",'Kelas',"Nama "], axis=1)
df.head(5)

Umur   Rerata UN  Rata­rata Nilai Sekolah      Hasil
0     17         87                       83      Lolos
1     17         83                       91      Lolos
2     18         91                       84      Lolos
3     17         90                      100      Lolos
4     17         82                       75  Coba lagi

In [5]:
df.shape

(28, 4)

In [6]:
# memisahkan data menjadi train dan test untuk menguji prediksi menjadi 20%
# disini data di acak menjadi random
from sklearn.model_selection import train_test_split
train, test = train_test_split(df,test_size = 0.2)

In [7]:
#memisahkan dataset menjadi features dan target
train_feat = train.iloc[:,:3]
train_targ = train["Hasil"]

In [8]:
test_feat = test.iloc[:,:3]
test_targ = test["Hasil"]

# Linear Reggresion
## Menguji keakuratan LR terhadap data train

In [9]:
#fit LR Models
lr.fit(train_feat, train_targ)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='lbfgs',
          tol=0.0001, verbose=0, warm_start=False)

In [10]:
# seberapa akurat dari data train
lr.score(train_feat,train_targ)

0.9545454545454546

In [11]:
# seberapa akurat dari data test
lr.score(test_feat,test_targ)

1.0

In [12]:
# melihat koefisien variable yang paling berpengaruh
lr.coef_

array([[-0.30600825,  0.3044778 ,  0.77178214]])

In [13]:
# hasil dari prediksi data train
lr.predict(train_feat)

array(['Coba lagi', 'Coba lagi', 'Coba lagi', 'Coba lagi', 'Lolos',
       'Lolos', 'Lolos', 'Coba lagi', 'Lolos', 'Coba lagi', 'Lolos',
       'Lolos', 'Coba lagi', 'Coba lagi', 'Lolos', 'Lolos', 'Lolos',
       'Lolos', 'Coba lagi', 'Lolos', 'Lolos', 'Lolos'], dtype=object)

In [14]:
# dari seluruh prediksi terdapat 1 error di data train
from sklearn.metrics import confusion_matrix
confusion_matrix(lr.predict(train_feat),train_targ)

array([[ 8,  1],
       [ 0, 13]], dtype=int64)

In [15]:
# dari seluruh prediksi tidak terdapat error di data train
confusion_matrix(lr.predict(test_feat),test_targ)

array([[1, 0],
       [0, 5]], dtype=int64)

## Mengimplementasikan prediksi menggunakan data asli

In [17]:
#mengimport data yang akan di prediksi
test1 = pd.read_csv('Test1.csv',sep = ';')
test1 = test1.drop(["NISN",'Kelas',"Nama "], axis=1)
test1

Umur   Rerata UN  Rerata Nilai Sekolah Hasil
0      16         80                    94    ? 
1      18         70                    97    ? 
2      17         84                    77    ? 
3      17         90                    89    ? 
4      17         92                    92    ? 
5      16         93                    81    ? 
6      18         91                    92    ? 
7      16         79                    78    ? 
8      18         87                    78    ? 
9      16         88                    95    ? 
10     18         89                    83     ?

In [18]:
#memisahkan dataset menjadi features dan target
test1_feat = test1.iloc[:,:3]

In [19]:
df_feat = df.iloc[:,:3]
df_targ = df["Hasil"]

In [20]:
# #fit LR Models
lr.fit(df_feat,df_targ)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='lbfgs',
          tol=0.0001, verbose=0, warm_start=False)

In [21]:
# seberapa akurat prediksi dari data
lr.score(df_feat,df_targ)

0.9642857142857143

In [22]:
# melihat koefisien variable yang paling berpengaruh
lr.coef_

array([[-0.30387279,  0.30747268,  0.7800669 ]])

In [23]:
# hasil dari prediksi data train
lr.predict(test1_feat)

array(['Lolos', 'Lolos', 'Coba lagi', 'Lolos', 'Lolos', 'Lolos', 'Lolos',
       'Coba lagi', 'Lolos', 'Lolos', 'Lolos'], dtype=object)

# Random Forest
## Menguji keakuratanRFC terhadap data train

In [25]:
rfc.fit(train_feat,train_targ)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [26]:
rfc.score(train_feat,train_targ)

1.0

In [27]:
rfc.score(test_feat,test_targ)

1.0

In [28]:
rfc.predict(train_feat)

array(['Coba lagi', 'Coba lagi', 'Coba lagi', 'Coba lagi', 'Lolos',
       'Lolos', 'Lolos', 'Coba lagi', 'Lolos', 'Coba lagi', 'Lolos',
       'Lolos', 'Lolos', 'Coba lagi', 'Lolos', 'Lolos', 'Lolos', 'Lolos',
       'Coba lagi', 'Lolos', 'Lolos', 'Lolos'], dtype=object)

In [29]:
confusion_matrix(rfc.predict(train_feat),train_targ)

array([[ 8,  0],
       [ 0, 14]], dtype=int64)

In [30]:
confusion_matrix(rfc.predict(test_feat),test_targ)

array([[1, 0],
       [0, 5]], dtype=int64)

## Mengimplementasikan prediksi menggunakan data asli

In [32]:
rfc.fit(df_feat,df_targ)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [33]:
rfc.score(df_feat,df_targ)

1.0

In [34]:
rfc.predict(test1_feat)

array(['Lolos', 'Lolos', 'Coba lagi', 'Lolos', 'Lolos', 'Lolos', 'Lolos',
       'Coba lagi', 'Lolos', 'Lolos', 'Lolos'], dtype=object)

# SFM
## Menguji keakuratan svc terhadap data train

In [36]:
import warnings
with warnings.catch_warnings():
    warnings.simplefilter('ignore')
    svc.fit(train_feat,train_targ)

In [37]:
svc.score(train_feat,train_targ)

0.7727272727272727

In [38]:
svc.score(test_feat,test_targ)

0.8333333333333334

In [39]:
svc.predict(train_feat)

array(['Lolos', 'Lolos', 'Coba lagi', 'Lolos', 'Lolos', 'Lolos', 'Lolos',
       'Lolos', 'Lolos', 'Coba lagi', 'Lolos', 'Lolos', 'Lolos',
       'Coba lagi', 'Lolos', 'Lolos', 'Lolos', 'Lolos', 'Lolos', 'Lolos',
       'Lolos', 'Lolos'], dtype=object)

In [40]:
confusion_matrix(svc.predict(train_feat),train_targ)

array([[ 3,  0],
       [ 5, 14]], dtype=int64)

In [41]:
confusion_matrix(svc.predict(test_feat),test_targ)

array([[0, 0],
       [1, 5]], dtype=int64)

In [42]:
svc.coef_

array([[-0.43038785, -0.00486463,  0.10764394]])

## Mengimplementasikan prediksi menggunakan data asli

In [44]:
with warnings.catch_warnings():
    warnings.simplefilter('ignore')
    svc.fit(df_feat,df_targ)

In [45]:
svc.score(df_feat,df_targ)

0.7857142857142857

In [46]:
svc.predict(test1_feat)

array(['Lolos', 'Lolos', 'Lolos', 'Lolos', 'Lolos', 'Lolos', 'Lolos',
       'Lolos', 'Coba lagi', 'Lolos', 'Lolos'], dtype=object)